CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERAL=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_PERIPHERAL=y
CONFIG_ZMK_BLE_CENTRAL=y
CONFIG_ZMK_BLE_DEVICE_NAME="Chocofi36"
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n